apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: kube-
build:
  artifacts:
    - image: kube1
      jib:
        project: com.iknowhow.poc.kubernetes:kube1
manifests:
  rawYaml:
    - k8s-*

#deploy:
#  kubectl:
#    manifests:
#      - k8s-*