apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kube1
  name: kube1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kube1
    spec:
      containers:
      - image: kube1
        name: kube1
        ports:
          - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: local-kube
        resources: {}
status: {}
